kind: pipeline
name: greeting

clone:
  disable: true
steps:

- name: es
  image: alpine
  commands: 
  - echo hola
  - echo mundo
- name: clone代码
  pull: if-not-exists
  image: alpine/git
  commands: 
  - echo hola
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL}
- name: 编译代码
    pull: if-not-exists
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - echo hola
    when:
      branch:
        - feature-*
        - develop
        - master
