kind: pipeline
name: greeting

clone:
  disable: true
steps:

- name: es
  image: alpine
  commands: 
  - echo hola
  - echo mundo
- name: ch
  image: alpine
  commands: 
  - echo hola
  - echo mundo
