kind: pipeline
name: greeting

clone:
  disable: true
steps:
- name: ddd
    image: alpine/git
    volumes:
      - name: dns
        path: /etc/hosts
    commands:
      - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL} .
    when:
      branch:
        exclude:
          - master
  

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo
volumes:
  - name: dns
    host:
      path: /etc/hosts
