kind: pipeline
name: greeting

clone:
  disable: true
steps:
- name: 测试获取
  image: alpine
  commands:
  - echo hello
  - echo world ${DRONE_GITHUB_CLIENT_ID}
  - echo ${DRONE_BRANCH}+${DRONE_GIT_HTTP_URL}
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL} .
  
- name: clone代码
    pull: if-not-exists
    image: alpine/git
    volumes:
      - name: dns
        path: /etc/hosts
    commands:
      - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL} .
    when:
      branch:
        exclude:
          - master
  

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo
volumes:
  - name: dns
    host:
      path: /etc/hosts
