kind: pipeline
type: docker
name: greetin构3

steps:
- name: en
  commands:
  - echo hello world

- name: fr
  image: alpine
  commands:
  - echo bonjour monde
  when:
      branch:
        exclude:
          - master
