kind: pipeline
name: greeting

clone:
  disable: true
steps:

- name: es
  image: alpine
  commands: 
  - echo hola
  - echo mundo
- name: clone代码
  pull: if-not-exists
  image: alpine/git
  commands: 
  - echo hola
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL}
- name: clone代码
  pull: if-not-exists
  image: alpine/git
  commands: 
  - echo hola
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL}
