kind: pipeline
name: greeting

clone:
  disable: true
steps:

- name: es
  image: alpine
  commands: 
  - echo hola
  - echo mundo
- name: clone代码
  pull: if-not-exists
  image: alpine/git
  commands: 
  - echo hola
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL}
  - name: 编译 CMS 代码
    pull: if-not-exists
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - name: go-pkg
        path: /go/pkg
    commands:
      - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - dotnet publish src/admin/CMS -c Release
    when:
      branch:
        - feature-*
        - develop
        - master
