kind: pipeline
name: greeting

clone:
  disable: true
steps:
- name: clone代码
  image: alpine
  commands:
  - echo hello
  - echo world ${DRONE_GITHUB_CLIENT_ID}
  - echo ${DRONE_BRANCH}+${DRONE_GIT_HTTP_URL}
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL} .

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo
