kind: pipeline
type: docker
name: greeting

steps:
- name: en
  image: alpine
  commands:
  - echo hello world
  when:
      branch:
        exclude:
          - master

- name: fr
  image: alpine
  commands:
  - echo bonjour monde
  when:
      branch:
        exclude:
          - master
