kind: pipeline
name: greeting

clone:
  disable: true
steps:

- name: es
  image: alpine
  commands: 
  - echo hola
  - echo mundo
- name: ch
  image: alpine/git
  commands: 
  - echo hola
  - git clone -b ${DRONE_BRANCH} ${DRONE_GIT_HTTP_URL}
