kind: pipeline
name: greeting

clone:
  disable: true
steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world ${DRONE_GITHUB_CLIENT_ID}

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo
