#stream test
kind: pipeline
name: stream
steps:
  - name: stream test
    image: ccr.ccs.tencentyun.com/star/stream-test-base
    commands:
      - echo 'Hello!'
      - echo ${DRONE_GITHUB_CLIENT_ID}
trigger:
  branch:
    - stream
  event:
    - pull_request
      
